#include "mapscript.h"

MapScript::MapScript()
{
    functions = QMap<QString,Function>();
    variables = QMap<QString,Variable>();

    functions.insert("map:on_started", Function("map:on_started"));
    functions.insert("map:on_update", Function("map:on_update"));

    variables.insert("map", Variable("map", "..."));
    variables.insert("game", Variable("game", "map:get_game()"));
}

MapScript::~MapScript() { }

MapScript::Function* MapScript::getFunction(QString name)
{
    auto iter = functions.find(name);
    if(iter != functions.end())
        return &iter.value();
    else
        return nullptr;
}

void MapScript::addSwitch(SwitchEntity switchEntity)
{
    // Create on active function for this script
    Function onActivate = Function(switchEntity.getName() + ":on_activated");

    // Create on_active function contents
    onActivate.addLine("game:set_value(\"" + switchEntity.getName() + "Active\",true)\n");

    // Add to functions
    functions.insert(onActivate.getName(), onActivate);

    // Create and add switch variable to map
    Variable switchVar = Variable(switchEntity.getName(), "map:get_entity(\"" + switchEntity.getName() + "\"");

    // Add the switch variable to the script
    variables.insert(switchVar.getName(), switchVar);
}

void MapScript::addDoor(const Door& door, QList<SwitchEntity> switches)
{
    Function& onStarted = functions.find("map:on_started").value();

    QString ifStatement;
    for(int i = 0; i < switches.size(); i++)
    {
        ifStatement += "if(game:get_value(\"" + switches[i].getName() + "Active\") == true";
        if(i != switches.size()-1)
            ifStatement += "and";
        else
            ifStatement += ") then";
    }

    onStarted.addLine(ifStatement);
    onStarted.addLine("map:open_doors(\"" + door.getName() + "\"");
}

void MapScript::writeToFile(QFile& file)
{
    file.open(QIODevice::WriteOnly);

    if(!file.isOpen())
        return;

    QTextStream out(&file);

    out << "-- This script file has been generated by the ProcLevelDesigner.\n";

    // Write all variables
    for(auto iter = variables.begin(); iter != variables.end(); iter++)
        out << iter.value().build() << "\n";

    // Write all functions
    for(auto iter = functions.begin(); iter != functions.end(); iter++)
        out << iter.value().build() << "\n";

    out << "-- End of generated script.\n";

    out.flush();
    file.flush();
    file.close();
}
